/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 Receive Data Source Select: UART_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 Transmit Data Source Select: UART0_TX pin */

/*! @name PORTA1 (number 35), J1[2]/D0/UART1_RX_TGTMCU
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTA2 (number 36), J1[4]/D1/UART1_TX_TGTMCU
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTB16 (number 62), E1/TSI_ELECTRODE1
  @{ */
#define BOARD_INITPINS_TSI_ELECTRODE_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_TSI_ELECTRODE_1_PIN 16U    /*!<@brief PORTB pin index: 16 */
                                                  /* @} */

/*! @name PORTB17 (number 63), E1/TSI_ELECTRODE2
  @{ */
#define BOARD_INITPINS_TSI_ELECTRODE_2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_TSI_ELECTRODE_2_PIN 17U    /*!<@brief PORTB pin index: 17 */
                                                  /* @} */

/*! @name PORTE29 (number 26), LED_RED
  @{ */
#define BOARD_INITPINS_LED_RED_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LED_RED_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LED_RED_PIN 29U    /*!<@brief PORTE pin index: 29 */
                                          /* @} */

/*! @name PORTD5 (number 98), J2[12]/D13/LED_GREEN
  @{ */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_GREEN_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_GREEN_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
